apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: mystudentapp
  labels:
    app: mystudentapp
spec:
  containers:
    - name: studentapp
      image: gauravgadilohar/op
      resources:
        requests:
          cpu: "50m"
          memory: "90Mi"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: studentapp
  namespace: mystudentapp
spec:
  type: LoadBalancer
  selector:
    app: mystudentapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080