apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Tomcat container port
  type: ClusterIP
