apiVersion: v1
kind: Service
metadata:
  name: studentapp
  labels:
    app: studentapp
spec:
  selector:
    app: studentapp
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Nginx container port
  type: ClusterIP
