apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployappback
  labels:
      app: deployappback
spec:
  replicas: 2  # desired state
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deployappback
  template:
    metadata:
      labels:
        app: deployappback
    spec:
      containers:
      - name: backendapp
        image: gauravgadilohar/op
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
# HorizontalPodAutoscaler configuration
apiVersion: autoscaling/v2beta2  # Changed to autoscaling/v2beta2 for better compatibility
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployappback
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Corrected field name
